"""
Auto-generated smoke tests — regenerated by write_smoke_tests.sh before each
edit to a src/ Python file.  Do not edit by hand; changes will be overwritten.

Tests:
  * Every .py module under src/ can be imported without errors
  * A freshly generated GameState has all expected starting entities
  * Tech tree is fully populated
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# -- Module imports (any syntax/import error will fail the test) --
import src.game_state
import src.generator
import src.gui.app
import src.gui.constants
import src.gui.energy_view
import src.gui.entities_panel
import src.gui.entity_view
import src.gui.galaxy_view
import src.gui.game_clock
import src.gui.game_view
import src.gui.ledger_view
import src.gui.main_menu
import src.gui.map_panel
import src.gui.nav_panel
import src.gui.new_game_panel
import src.gui.pause_menu
import src.gui.queue_view
import src.gui.taskbar
import src.gui.tech_view
import src.gui.tooltip
import src.gui.widgets
import src.models.celestial
import src.models.entity
import src.models.ledger
import src.models.resource
import src.models.tech
import src.simulation

# -- Game-state assertions --
from src.game_state import GameState
from src.generator import MapGenerator
from src.models.tech import TECH_TREE
from src.models.entity import STARTING_ENTITIES, BotType, StructureType

gen = MapGenerator(seed=1, num_solar_systems=3)
gs  = GameState.new_game(gen.generate())

assert gs.entity_roster.total('structure', 'factory')           == 1, 'factory missing'
assert gs.entity_roster.total('structure', 'power_plant_solar') == 1, 'solar plant missing'
assert gs.entity_roster.total('structure', 'power_plant_wind')  == 1, 'wind plant missing'
assert gs.entity_roster.total('structure', 'research_array')    == 1, 'research array missing'
assert gs.entity_roster.total('bot',       'miner')             == 1, 'miner bot missing'
assert gs.entity_roster.total('bot',       'constructor')       == 1, 'constructor bot missing'
assert gs.entity_roster.total('ship',      'probe')             == 1, 'probe missing'
assert gs.entity_roster.total('ship',      'drop_ship')         == 1, 'drop ship missing'
assert gs.entity_roster.total('ship',      'mining_vessel')     == 1, 'mining vessel missing'
assert len(TECH_TREE) >= 13,                                          'tech tree incomplete'
assert BotType.MINER   == 'miner',                                    'BotType.MINER missing'
assert gs.tech is not None,                                           'TechState missing'

# Verify all StructureType values in POWER_PLANT_SPECS are valid StructureType members
from src.models.entity import POWER_PLANT_SPECS
for st in POWER_PLANT_SPECS:
    assert isinstance(st, StructureType), f'Bad key in POWER_PLANT_SPECS: {st}'

print(
    f'Smoke tests OK — '
    f'{len(STARTING_ENTITIES)} starting entities, '
    f'{len(TECH_TREE)} tech nodes, '
    f'{len(POWER_PLANT_SPECS)} power plant specs.'
)
