#!/usr/bin/env bash
# write_smoke_tests.sh — PreToolUse hook
#
# Runs before Edit/Write tool calls. Reads the tool input JSON from stdin,
# checks if a Python source file under src/ is being modified, and if so
# regenerates scripts/smoke_tests.py with:
#   1. An import statement for every .py module under src/
#   2. Base game-state assertions against a freshly generated galaxy

REPO="/c/Users/Admin/code"
PROJECT="UniversalAssemblers"
PYTHON="/c/Users/Admin/anaconda3/python.exe"
SRC="$REPO/$PROJECT/src"
OUT="$REPO/$PROJECT/scripts/smoke_tests.py"

# ── 1. Parse the file path being edited from stdin JSON ──────────────────────
TOOL_INPUT=$(cat)
FILE_PATH=$(echo "$TOOL_INPUT" | "$PYTHON" -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('tool_input', {}).get('file_path', ''))
except Exception:
    print('')
" 2>/dev/null)

# Only act on .py files that live under UniversalAssemblers/src/
case "$FILE_PATH" in
    *.py) ;;
    *) exit 0 ;;
esac
echo "$FILE_PATH" | grep -q "${PROJECT}/src" || exit 0

# ── 2. Write the header of smoke_tests.py ────────────────────────────────────
cat > "$OUT" << 'PYEOF'
"""
Auto-generated smoke tests — regenerated by write_smoke_tests.sh before each
edit to a src/ Python file.  Do not edit by hand; changes will be overwritten.

Tests:
  • Every .py module under src/ can be imported without errors
  • A freshly generated GameState has all expected starting entities
  • Tech tree is fully populated
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

PYEOF

# ── 3. Append one import line per src/ module ────────────────────────────────
echo "# -- Module imports (any syntax/import error will fail the test) --" >> "$OUT"

find "$SRC" -name "*.py" \
    ! -name "__init__.py" \
    ! -path "*/__pycache__/*" \
| sort | while read -r pyfile; do
    # Convert absolute path → dotted module name
    # e.g. .../src/gui/app.py  →  src.gui.app
    rel="${pyfile#$REPO/$PROJECT/}"   # src/gui/app.py
    module="${rel%.py}"               # src/gui/app
    module="${module//\//.}"          # src.gui.app
    echo "import $module" >> "$OUT"
done

# ── 4. Append base game-state assertions ─────────────────────────────────────
cat >> "$OUT" << 'PYEOF'

# -- Game-state assertions --
from src.game_state import GameState
from src.generator import MapGenerator
from src.models.tech import TECH_TREE
from src.models.entity import STARTING_ENTITIES, BotType, StructureType

gen = MapGenerator(seed=1, num_solar_systems=3)
gs  = GameState.new_game(gen.generate())

assert gs.entity_roster.total('structure', 'factory')           == 1, 'factory missing'
assert gs.entity_roster.total('structure', 'power_plant_solar') == 1, 'solar plant missing'
assert gs.entity_roster.total('structure', 'power_plant_wind')  == 1, 'wind plant missing'
assert gs.entity_roster.total('structure', 'research_array')    == 1, 'research array missing'
assert gs.entity_roster.total('bot',       'miner')             == 1, 'miner bot missing'
assert gs.entity_roster.total('bot',       'constructor')       == 1, 'constructor bot missing'
assert gs.entity_roster.total('ship',      'probe')             == 1, 'probe missing'
assert gs.entity_roster.total('ship',      'drop_ship')         == 1, 'drop ship missing'
assert gs.entity_roster.total('ship',      'mining_vessel')     == 1, 'mining vessel missing'
assert len(TECH_TREE) >= 13,                                          'tech tree incomplete'
assert BotType.MINER   == 'miner',                                    'BotType.MINER missing'
assert gs.tech is not None,                                           'TechState missing'

# Verify all StructureType values in POWER_PLANT_SPECS are valid StructureType members
from src.models.entity import POWER_PLANT_SPECS
for st in POWER_PLANT_SPECS:
    assert isinstance(st, StructureType), f'Bad key in POWER_PLANT_SPECS: {st}'

print(
    f'Smoke tests OK — '
    f'{len(STARTING_ENTITIES)} starting entities, '
    f'{len(TECH_TREE)} tech nodes, '
    f'{len(POWER_PLANT_SPECS)} power plant specs.'
)
PYEOF

echo "[smoke-gen] Regenerated smoke_tests.py (triggered by: $FILE_PATH)"
exit 0
